(()=>{
'use strict';
const R12V='r12',PLANKEY='tbmaplan12',FEEDBACKKEY='tbmafeedback12';
document.title='Tomi BMA Field r12';
const sub=document.querySelector('header .sub');if(sub)sub.textContent='Bietigheim · REALTEST r12 · Montage-Planeditor';
const st=document.createElement('style');st.textContent=`
.planeditbar{display:none;gap:8px;align-items:center;flex-wrap:wrap;background:#fff7e8;border:1px solid #f0c36a;border-radius:12px;padding:8px;margin-bottom:8px}.planeditbar.onv{display:flex}.planeditbar button{min-height:44px;border:1px solid #d7e0e7;border-radius:10px;background:white;font-weight:900;padding:0 12px}.planmode{font-weight:900;color:#8a4b00}.testbadge{display:inline-flex;border-radius:999px;background:#ffe8b3;color:#7a4600;padding:4px 8px;font-size:11px;font-weight:900}.editmenu{display:grid;grid-template-columns:1fr 1fr;gap:8px}.editmenu button{min-height:58px;border:1px solid #d7e0e7;border-radius:12px;background:white;text-align:left;padding:10px;font-weight:900}.editmenu button small{display:block;font-weight:400;color:#6a7a88;margin-top:3px}.danger{color:#b42318!important;border-color:#efb4ae!important}.feedbackbtn{background:#fff8e7!important;border-color:#e7bd55!important}.planhist{display:grid;gap:7px;max-height:46vh;overflow:auto}.planhistrow{border:1px solid #d7e0e7;border-radius:10px;padding:9px;background:#f8fafb}.planhint{padding:10px;border-radius:10px;background:#eef4fb;color:#254d71;font-size:13px;margin:8px 0}.pdet{cursor:pointer}.pdet .pbase{fill:#f7f9fa;stroke:#596773;stroke-width:2.5}.pdet .pouter{fill:none;stroke:#0b3158;stroke-width:2;stroke-dasharray:4 3}.pdet .psiren{fill:#f5a623;stroke:#8a4b00;stroke-width:1}.pdet .phm{fill:#ca2c28;stroke:#861614;stroke-width:2}.pdet .plabel{font-size:10px;font-weight:900;fill:#17324d;text-anchor:middle}.pdet.selected .pbase,.pdet.selected .phm{stroke:#f5a623;stroke-width:5}.pdet.added .pbase{fill:#eaf7ef}.pdet .pchanged{fill:#7c3aed}.inline2{display:grid;grid-template-columns:1fr 1fr;gap:8px}.formactions{display:grid;grid-template-columns:1fr 1fr;gap:8px;margin-top:12px}.formactions button{min-height:50px;border:1px solid #d7e0e7;border-radius:12px;background:white;font-weight:900}.formactions .primary{background:#16834f;color:white;border:0}.feedbacktype{display:grid;grid-template-columns:1fr 1fr;gap:8px}.feedbacktype button{min-height:52px;border:1px solid #d7e0e7;border-radius:12px;background:white;font-weight:900}.feedbacktype button.on{background:#0b3158;color:white}.renpreview{font-family:monospace;white-space:pre-wrap;background:#f8fafb;border:1px solid #d7e0e7;border-radius:10px;padding:10px;max-height:220px;overflow:auto;margin-top:8px}@media(max-width:700px){.editmenu,.inline2{grid-template-columns:1fr}}
`;document.head.appendChild(st);

[['2.21 Klassenraum','2.21 Flur'],['2.21.1 Nebenraum','2.21.1 Flur'],['2.20 Klassenraum','2.20 Flur'],['2.14 Mehrzweckraum','2.14 WC J'],['2.16 Klassenraum','2.16 Klasse']].forEach(([a,b])=>document.querySelectorAll('#pv text').forEach(x=>{if(x.textContent===a)x.textContent=b}));
const pv=document.querySelector('#pv'),planbox=pv.querySelector('.planbox');
planbox.insertAdjacentHTML('beforebegin','<div id="planEditBar" class="planeditbar"><span class="testbadge">TESTVERSION</span><button id="planMenuBtn">☰ Montage-Menü</button><span id="planModeLabel" class="planmode">Prüfmodus</span><button id="planUndoBtn">↶ Rückgängig</button><span id="planEditHint" class="meta">Melder antippen = Montage öffnen.</span></div>');
const gate=document.querySelector('#gate');gate.insertAdjacentHTML('beforebegin',`
<div id="planMenu" class="overlay"><div class="sheet"><div style="display:flex;justify-content:space-between;align-items:center"><div><h2 style="margin:0">Montage-Menü</h2><div class="meta">Laufkarte bearbeiten · TESTVERSION</div></div><button id="planMenuClose">×</button></div><div class="planhint">Änderungen werden lokal gespeichert und im Änderungsverlauf protokolliert. Original-Projektdaten bleiben nachvollziehbar.</div><div class="editmenu"><button data-planmode="add">＋ Melder hinzufügen<small>Position antippen, Typ und Nummer festlegen.</small></button><button data-planmode="move">↔ Melder verschieben<small>Melder wählen, danach neue Position antippen.</small></button><button data-planmode="remove" class="danger">− Melder entfernen<small>Bleibt im Änderungsverlauf nachvollziehbar.</small></button><button data-planmode="manualnum"># Manuell nummerieren<small>Melder antippen und neue Nummer eingeben.</small></button><button id="autoNumberBtn">⇢ Automatisch nummerieren<small>Sichtbare Laufkarte nach Position neu nummerieren.</small></button><button id="planHistoryBtn">☷ Planänderungen<small>Alle Änderungen prüfen.</small></button><button id="feedbackSuggestionBtn" class="feedbackbtn">💡 Vorschlag<small>Idee für die Testversion.</small></button><button id="feedbackBugBtn" class="feedbackbtn">🧪 Das funktioniert nicht<small>Fehler mit Diagnoseinfos melden.</small></button></div><button id="planNormalBtn" class="msecondary" style="margin-top:10px">Prüfmodus aktivieren</button></div></div>
<div id="planAdd" class="overlay"><div class="sheet"><h2>Melder hinzufügen</h2><div id="planAddPos" class="meta"></div><div class="grid"><div class="field"><label>Typ</label><select id="planAddType"><option value="RM">Rauchmelder</option><option value="RM_ZD">ZD · Rauchmelder</option><option value="SCT">Rauchmelder mit Sirene</option><option value="SCT_MULTI">Multisensormelder mit Sirene</option><option value="HM">Handmelder</option><option value="DKM">Druckknopfmelder</option></select></div><div class="field"><label>Loop</label><select id="planAddLoop">${Array.from({length:9},(_,i)=>`<option>L0${i+1}</option>`).join('')}</select></div><div class="field"><label>Nummerierung</label><select id="planAddNumMode"><option value="manual">Manuell</option><option value="auto">Automatisch</option></select></div><div class="field"><label>Meldernummer</label><input id="planAddAddr" placeholder="z. B. 58/5"></div><div class="field"><label>Meldegruppe für Automatik</label><input id="planAddGroup" inputmode="numeric" placeholder="z. B. 58"></div><div class="field"><label>Raum</label><input id="planAddRoom" readonly></div></div><div class="formactions"><button id="planAddCancel">Abbrechen</button><button id="planAddSave" class="primary">Melder hinzufügen</button></div></div></div>
<div id="planManualNum" class="overlay"><div class="sheet"><h2>Melder manuell nummerieren</h2><div id="planManualWho" class="meta"></div><div class="field" style="margin-top:10px"><label>Neue Meldernummer</label><input id="planManualAddr" placeholder="z. B. 58/6"></div><div class="formactions"><button id="planManualCancel">Abbrechen</button><button id="planManualSave" class="primary">Nummer übernehmen</button></div></div></div>
<div id="planAutoNum" class="overlay"><div class="sheet"><h2>Automatische Nummerierung</h2><div class="planhint">Nur sichtbare Melder dieser Test-Laufkarte. Reihenfolge: oben nach unten, links nach rechts. Vorschau vor Übernahme.</div><div class="inline2"><div class="field"><label>Meldegruppe</label><input id="autoGroup" inputmode="numeric" value="58"></div><div class="field"><label>Startnummer</label><input id="autoStart" inputmode="numeric" value="1"></div></div><div id="autoPreview" class="renpreview">Vorschau</div><div class="formactions"><button id="autoCancel">Abbrechen</button><button id="autoApply" class="primary">Nummerierung übernehmen</button></div></div></div>
<div id="planHistory" class="overlay"><div class="sheet"><div style="display:flex;justify-content:space-between;align-items:center"><div><h2 style="margin:0">Planänderungen</h2><div class="meta">Lokaler Änderungsverlauf</div></div><button id="planHistoryClose">×</button></div><div id="planHistoryList" class="planhist" style="margin-top:10px"></div></div></div>
<div id="feedbackSheet" class="overlay"><div class="sheet"><h2>Test-Feedback</h2><div class="meta">Version, Modus, Uhrzeit und Gerätedaten werden automatisch ergänzt.</div><div class="feedbacktype" style="margin-top:10px"><button data-ft="Vorschlag">💡 Vorschlag</button><button data-ft="Funktioniert nicht">🧪 Funktioniert nicht</button></div><div class="field" style="margin-top:10px"><label>Beschreibung</label><textarea id="feedbackText" placeholder="Was soll besser werden oder was funktioniert nicht?"></textarea></div><div id="feedbackDiag" class="mnotice"></div><div class="formactions"><button id="feedbackSave">Lokal speichern</button><button id="feedbackShare" class="primary">Teilen / E-Mail</button></div><button id="feedbackClose" class="msecondary" style="margin-top:8px">Schließen</button></div></div>`);

let plan=(()=>{try{return JSON.parse(localStorage.getItem(PLANKEY)||'null')||{added:[],removed:{},overrides:{},positions:{},history:[]}}catch(e){return{added:[],removed:{},overrides:{},positions:{},history:[]}}})();
let feedback=(()=>{try{return JSON.parse(localStorage.getItem(FEEDBACKKEY)||'[]')}catch(e){return[]}})();
function ensurePlan(){plan.added=Array.isArray(plan.added)?plan.added:[];plan.removed=plan.removed||{};plan.overrides=plan.overrides||{};plan.positions=plan.positions||{};plan.history=Array.isArray(plan.history)?plan.history:[]}ensurePlan();
const oldPersist=persist;currentPayload=()=>({version:R12V,db,svc,bmz,montage,plan,feedback});persist=()=>{oldPersist();localStorage.setItem(PLANKEY,JSON.stringify(plan));localStorage.setItem(FEEDBACKKEY,JSON.stringify(feedback));meta.appVersion=R12V;localStorage.setItem('tbmameta8',JSON.stringify(meta))};
backupPackage=()=>({app:'Tomi BMA Field',format:'tbma-field-backup',schema:3,version:R12V,exportedAt:new Date().toISOString(),quarter:cq,data:{db,svc,bmz,montage,plan,feedback}});
loadBackupFile=async file=>{if(!file)return;try{const pkg=JSON.parse(await file.text()),data=pkg&&pkg.format==='tbma-field-backup'?pkg.data:(pkg&&pkg.data&&pkg.data.db?pkg.data:null);if(!data||typeof data.db!=='object')throw 0;snapshot('Sicherung vor Import');db=data.db||{};svc=data.svc||{};bmz=data.bmz||{};montage=data.montage||{};plan=data.plan||{added:[],removed:{},overrides:{},positions:{},history:[]};feedback=data.feedback||[];ensurePlan();persist();snapshot('Importierte Sicherung');lastBackupMessage='Sicherung geladen: '+file.name;updateBackupStatus();render();alert('Sicherung erfolgreich geladen.')}catch(e){alert('Sicherungsdatei ist ungültig oder beschädigt.')}finally{$('#backupfile').value=''}};
$('#backupfile').onchange=e=>loadBackupFile(e.target.files&&e.target.files[0]);

const PLAN_ROOMS=[{no:'2.21',name:'Flur',x:45,y:50,w:300,h:220},{no:'2.21.1',name:'Flur',x:345,y:50,w:280,h:220},{no:'2.20',name:'Flur',x:625,y:50,w:330,h:220},{no:'2.07',name:'Flur',x:45,y:270,w:910,h:110},{no:'2.14',name:'WC J',x:45,y:380,w:455,h:190},{no:'2.16',name:'Klasse',x:500,y:380,w:455,h:190}];
let planMode='normal',planSelectedId=null,planClickPoint=null,manualNumId=null,feedbackType='Vorschlag';
const allMontageDevices=()=>[...MONTAGE_D,...plan.added].filter(d=>!plan.removed[d.id]).map(d=>({...d,...(plan.overrides[d.id]||{})}));
const montageById=id=>allMontageDevices().find(d=>d.id===id)||null;
const originalMontageById=id=>[...MONTAGE_D,...plan.added].find(d=>d.id===id)||null;
const roomAt=(x,y)=>PLAN_ROOMS.find(r=>x>=r.x&&x<=r.x+r.w&&y>=r.y&&y<=r.y+r.h)||null;
const visiblePlanDevices=()=>allMontageDevices().filter(d=>PLAN_ROOMS.some(r=>r.no===d.roomNo));
function planPos(d){if(plan.positions[d.id])return plan.positions[d.id];const r=PLAN_ROOMS.find(x=>x.no===d.roomNo)||PLAN_ROOMS[0],same=visiblePlanDevices().filter(x=>x.roomNo===d.roomNo),idx=Math.max(0,same.findIndex(x=>x.id===d.id)),cols=Math.max(1,Math.ceil(Math.sqrt(same.length||1))),rows=Math.max(1,Math.ceil((same.length||1)/cols)),col=idx%cols,row=Math.floor(idx/cols);return{x:Math.round(r.x+45+(r.w-90)*(cols===1?.5:col/(cols-1))),y:Math.round(r.y+70+(r.h-100)*(rows===1?.5:row/(rows-1)))}}
function planSnapshot(id){const d=originalMontageById(id),o=plan.overrides[id]||{},p=plan.positions[id]||null;return d?{device:{...d},override:{...o},position:p?{...p}:null,removed:!!plan.removed[id]}:null}
function planAudit(type,id,before,after,note=''){plan.history.push({ts:new Date().toISOString(),type,id,before:before||null,after:after||null,note});if(plan.history.length>500)plan.history=plan.history.slice(-500);persist()}
function planDeviceSvg(d){const p=planPos(d),sel=planSelectedId===d.id?'selected':'',added=plan.added.some(x=>x.id===d.id)?'added':'',changed=(plan.overrides[d.id]||plan.positions[d.id])?'1':'0',hm=['HM','DKM'].includes(d.cat),zd=d.cat==='RM_ZD',sir=['SCT','SCT_MULTI'].includes(d.cat);return `<g class="pdet ${sel} ${added}" data-pid="${d.id}" transform="translate(${p.x} ${p.y})">${hm?'<rect class="phm" x="-16" y="-18" width="32" height="36" rx="4"/>':`${zd?'<circle class="pouter" r="25"/>':''}<circle class="pbase" r="19"/>`}${sir?'<circle class="psiren" cx="16" cy="-15" r="8"/><text class="plabel" x="16" y="-12" style="font-size:8px">S</text>':''}${changed?'<circle class="pchanged" cx="-17" cy="-16" r="5"/>':''}<text class="plabel" y="34">${escapeHtml(d.addr||'—')}</text></g>`}
function updatePlanModeUI(){const m={normal:['Prüfmodus','Melder antippen = Montage öffnen.'],add:['Melder hinzufügen','Position auf der Laufkarte antippen.'],move:['Melder verschieben',planSelectedId?'Neue Position antippen.':'Zuerst einen Melder antippen.'],remove:['Melder entfernen','Zu entfernenden Melder antippen.'],manualnum:['Manuell nummerieren','Melder antippen und Nummer eingeben.']}[planMode];$('#planModeLabel').textContent=m[0];$('#planEditHint').textContent=m[1]}
function renderMontagePlan(){if(cq!=='Montage')return;const a=visiblePlanDevices();$('#devs').innerHTML=a.map(planDeviceSvg).join('');document.querySelectorAll('.pdet').forEach(e=>e.onclick=ev=>{ev.stopPropagation();handlePlanDeviceTap(e.dataset.pid)});$('#prog').textContent=`Montage-Laufkarte: ${a.length} sichtbare Positionen · ${allMontageDevices().length} Projektpositionen`;updatePlanModeUI()}
function setPlanMode(m){planMode=m;planSelectedId=null;$('#planMenu').classList.remove('show');updatePlanModeUI();renderMontagePlan()}
function svgPoint(ev){const svg=document.querySelector('#pv svg.plan'),pt=svg.createSVGPoint();pt.x=ev.clientX;pt.y=ev.clientY;const p=pt.matrixTransform(svg.getScreenCTM().inverse());return{x:Math.max(30,Math.min(970,Math.round(p.x))),y:Math.max(30,Math.min(590,Math.round(p.y)))}}
function handlePlanDeviceTap(id){const d=montageById(id);if(!d)return;if(planMode==='normal')return openMontage(d);if(planMode==='move'){planSelectedId=id;updatePlanModeUI();return renderMontagePlan()}if(planMode==='remove'){if(!confirm(`${d.addr} · ${mtypeLabel(d)}\n\nMelder aus der Laufkarte entfernen?`))return;const before=planSnapshot(id);plan.removed[id]=true;planAudit('Entfernt',id,before,planSnapshot(id),'Melder aus Montageplan entfernt');renderMontage();return renderMontagePlan()}if(planMode==='manualnum')openManualNumber(id)}
function handlePlanCanvasTap(ev){if(cq!=='Montage'||planMode==='normal'||ev.target.closest('.pdet'))return;const p=svgPoint(ev),room=roomAt(p.x,p.y);if(!room)return alert('Bitte Position innerhalb eines Raums wählen.');if(planMode==='add'){planClickPoint={...p,room};return openAddMelder()}if(planMode==='move'&&planSelectedId){const before=planSnapshot(planSelectedId),d=montageById(planSelectedId);plan.positions[planSelectedId]={x:p.x,y:p.y};plan.overrides[planSelectedId]={...(plan.overrides[planSelectedId]||{}),roomNo:room.no,room:room.name,floor:'2. OG'};planAudit('Verschoben',planSelectedId,before,planSnapshot(planSelectedId),`${d.addr} nach Raum ${room.no} verschoben`);planSelectedId=null;renderMontage();renderMontagePlan()}}
function nextAutoAddress(g){const re=new RegExp('^'+String(g).replace(/[.*+?^${}()|[\]\\]/g,'\\$&')+'/(\\d+)$'),nums=allMontageDevices().map(d=>String(d.addr||'').match(re)).filter(Boolean).map(m=>+m[1]);return `${g}/${(nums.length?Math.max(...nums):0)+1}`}
function openAddMelder(){const r=planClickPoint.room;$('#planAddPos').textContent=`Position ${planClickPoint.x} / ${planClickPoint.y} · Raum ${r.no} ${r.name}`;$('#planAddRoom').value=r.no+' '+r.name;$('#planAddAddr').value='';$('#planAddGroup').value='';$('#planAdd').classList.add('show')}
function typeMeta(c){return({RM:['Optischer Rauchmelder',false,false],RM_ZD:['Optischer Rauchmelder in Zwischendecke (ZD)',true,false],SCT:['Optischer Rauchmelder mit akustischem Signalgeber',false,true],SCT_MULTI:['Multisensormelder mit akustischem Signalgeber',false,true],HM:['Handmelder',false,false],DKM:['Druckknopfmelder',false,false]}[c]||[c,false,false])}
function saveAddedMelder(){if(!planClickPoint)return;const cat=$('#planAddType').value,mode=$('#planAddNumMode').value,loop=$('#planAddLoop').value,g=$('#planAddGroup').value.trim();let addr=$('#planAddAddr').value.trim();if(mode==='auto'){if(!g)return alert('Meldegruppe eingeben.');addr=nextAutoAddress(g)}if(!addr)return alert('Meldernummer eingeben.');if(allMontageDevices().some(d=>d.addr===addr&&d.loop===loop)&&!confirm(`Nummer ${addr} existiert bereits. Trotzdem hinzufügen?`))return;const tm=typeMeta(cat),id='N'+Date.now(),r=planClickPoint.room,d={id,rid:'NEU',floor:'2. OG',roomNo:r.no,room:r.name,loop,addr,cat,typ:tm[0],zd:tm[1],ak:tm[2],added:true};plan.added.push(d);plan.positions[id]={x:planClickPoint.x,y:planClickPoint.y};planAudit('Hinzugefügt',id,null,planSnapshot(id),`Neuer ${mtypeLabel(d)} in Raum ${r.no}`);$('#planAdd').classList.remove('show');planClickPoint=null;renderMontage();renderMontagePlan()}
function openManualNumber(id){manualNumId=id;const d=montageById(id);$('#planManualWho').textContent=`${d.addr} · ${mtypeLabel(d)} · ${d.roomNo} ${d.room}`;$('#planManualAddr').value=d.addr||'';$('#planManualNum').classList.add('show')}
function applyManualNumber(){const d=montageById(manualNumId),v=$('#planManualAddr').value.trim();if(!d||!v)return;if(allMontageDevices().some(x=>x.id!==d.id&&x.addr===v&&x.loop===d.loop)&&!confirm(`Nummer ${v} existiert bereits. Trotzdem übernehmen?`))return;const before=planSnapshot(d.id);plan.overrides[d.id]={...(plan.overrides[d.id]||{}),addr:v};planAudit('Manuell nummeriert',d.id,before,planSnapshot(d.id),`${d.addr} → ${v}`);$('#planManualNum').classList.remove('show');renderMontage();renderMontagePlan()}
function autoNumberPreview(){const g=$('#autoGroup').value.trim(),start=Number($('#autoStart').value||1),a=visiblePlanDevices().slice().sort((a,b)=>{const A=planPos(a),B=planPos(b);return A.y-B.y||A.x-B.x});if(!g||!Number.isFinite(start))return[];const rows=a.map((d,i)=>({id:d.id,old:d.addr,new:`${g}/${start+i}`}));$('#autoPreview').textContent=rows.map(x=>`${x.old}  →  ${x.new}`).join('\n')||'Keine Melder sichtbar.';return rows}
function applyAutoNumber(){const rows=autoNumberPreview();if(!rows.length||!confirm(`${rows.length} Melder automatisch neu nummerieren?`))return;rows.forEach(x=>{const before=planSnapshot(x.id);plan.overrides[x.id]={...(plan.overrides[x.id]||{}),addr:x.new};planAudit('Automatisch nummeriert',x.id,before,planSnapshot(x.id),`${x.old} → ${x.new}`)});$('#planAutoNum').classList.remove('show');renderMontage();renderMontagePlan()}
function restorePlanSnapshot(id,s){if(!s)return;if(s.removed)plan.removed[id]=true;else delete plan.removed[id];if(s.override&&Object.keys(s.override).length)plan.overrides[id]={...s.override};else delete plan.overrides[id];if(s.position)plan.positions[id]={...s.position};else delete plan.positions[id]}
function undoPlanChange(){if(!plan.history.length)return alert('Keine Planänderung zum Rückgängigmachen.');const h=plan.history.pop();if(h.type==='Hinzugefügt'){plan.added=plan.added.filter(x=>x.id!==h.id);delete plan.positions[h.id];delete plan.overrides[h.id];delete plan.removed[h.id]}else restorePlanSnapshot(h.id,h.before);persist();renderMontage();renderMontagePlan();alert('Letzte Planänderung wurde rückgängig gemacht.')}
function showPlanHistory(){const a=plan.history.slice().reverse();$('#planHistoryList').innerHTML=a.length?a.map(h=>`<div class="planhistrow"><b>${escapeHtml(h.type)} · ${escapeHtml(h.id||'')}</b><div>${escapeHtml(h.note||'')}</div><div class="meta">${new Date(h.ts).toLocaleString('de-DE')}</div></div>`).join(''):'<div class="meta">Noch keine Planänderungen.</div>';$('#planHistory').classList.add('show')}
function openFeedback(t){feedbackType=t;document.querySelectorAll('[data-ft]').forEach(b=>b.classList.toggle('on',b.dataset.ft===t));$('#feedbackText').value='';updateFeedbackDiag();$('#feedbackSheet').classList.add('show')}
function updateFeedbackDiag(){$('#feedbackDiag').textContent=`Diagnose: ${R12V} · ${cq||'kein Modus'} · ${navigator.onLine?'online':'offline'} · ${new Date().toLocaleString('de-DE')}`}
function feedbackPayload(){return{ts:new Date().toISOString(),type:feedbackType,text:$('#feedbackText').value.trim(),version:R12V,work:cq,planMode,online:navigator.onLine,userAgent:navigator.userAgent}}
function storeFeedback(show=true){const f=feedbackPayload();if(!f.text){alert('Beschreibung eingeben.');return null}feedback.push(f);if(feedback.length>200)feedback=feedback.slice(-200);persist();if(show)alert('Feedback lokal gespeichert.');return f}
async function shareFeedback(){const f=storeFeedback(false);if(!f)return;const text=`Tomi BMA Field ${f.version}\n${f.type}\n\n${f.text}\n\nModus: ${f.work}\nPlanmodus: ${f.planMode}\nOnline: ${f.online}\nZeit: ${new Date(f.ts).toLocaleString('de-DE')}\nGerät: ${f.userAgent}`;try{if(navigator.share){await navigator.share({title:`Tomi BMA Field – ${f.type}`,text});return}}catch(e){}location.href=`mailto:tpoljarevic@sectus.de?subject=${encodeURIComponent('Tomi BMA Field – '+f.type+' – '+R12V)}&body=${encodeURIComponent(text)}`}

montageFilterData=()=>{const q=($('#msearch')?.value||'').trim().toLowerCase(),lp=$('#mloop')?.value||'',fl=$('#mfloor')?.value||'',ty=$('#mtype')?.value||'',stf=$('#mstatefilter')?.value||'';return allMontageDevices().filter(d=>{const hay=[d.addr,d.roomNo,d.room,d.loop,d.floor,d.typ,d.cat,d.id].join(' ').toLowerCase();return(!q||hay.includes(q))&&(!lp||d.loop===lp)&&(!fl||d.floor===fl)&&(!ty||d.cat===ty)&&(!stf||mstate(d)===stf)})};
renderMontage=()=>{setupMontageFilters();$('#montageTools').style.display='block';const all=allMontageDevices(),dn=all.filter(d=>mstate(d)==='done').length,pn=all.filter(d=>mstate(d)==='part').length;$('#mtotal').textContent=all.length;$('#mdone').textContent=dn;$('#mpart').textContent=pn;$('#mopen').textContent=all.length-dn-pn;const a=montageFilterData();$('#prog').textContent=`Montage Bietigheim: ${dn} / ${all.length} Positionen fertig`;$('#cards').innerHTML=a.map(d=>{const s=mstate(d),pc=mprogressCount(d),pct=Math.round(pc[0]/pc[1]*100),r=mrec(d);return `<button class="card mcard ${s==='done'?'donecard':s==='part'?'partcard':''}" data-mid="${d.id}"><div class="mline"><div class="addr">${d.addr||'—'}</div><span class="mbadge ${mtypeClass(d)}">${mtypeLabel(d)}</span><span class="mbadge ${s==='done'?'ok':'open'}">${s==='done'?'Fertig':s==='part'?'In Arbeit':'Offen'}</span></div><div class="meta">${d.floor} · ${d.roomNo} · ${d.room} · ${d.loop}</div><div class="meta">${pc[0]} / ${pc[1]} Montageschritte${r.sn?' · SN: '+escapeHtml(r.sn):''}${r.hasPhoto?' · 📷':''}</div><div class="mprogress"><span style="width:${pct}%"></span></div></button>`}).join('');document.querySelectorAll('[data-mid]').forEach(e=>e.onclick=()=>openMontage(montageById(e.dataset.mid)))};
nextMontage=()=>{saveMontageFields();let a=montageFilterData(),i=a.findIndex(d=>d.id===mcur?.id),n=a[(i+1+a.length)%a.length]||allMontageDevices()[0];openMontage(n)};
enterMontageMode=()=>{$('#tp').style.display='';$('#tp').textContent='Laufkarte';$('#tb').style.display='none';$('#tl').textContent='Montageliste';$('#cat').style.display='none';$('#planEditBar').classList.add('onv');renderMontage();renderMontagePlan()};
leaveMontageMode=()=>{$('#tp').style.display='';$('#tb').style.display='';$('#tl').textContent='Liste';$('#cat').style.display='';$('#montageTools').style.display='none';$('#planEditBar').classList.remove('onv');planMode='normal';planSelectedId=null};
const oldRender=render;render=()=>{if(!cq)return;if(cq==='Montage'){enterMontageMode();updateBackupStatus();return}leaveMontageMode();oldRender()};

$('#tp').onclick=()=>{view('p');if(cq==='Montage')renderMontagePlan()};$('#tl').onclick=()=>{view('l');if(cq==='Montage')renderMontage()};
document.querySelector('#pv svg.plan').addEventListener('click',handlePlanCanvasTap);
$('#planMenuBtn').onclick=()=>$('#planMenu').classList.add('show');$('#planMenuClose').onclick=()=>$('#planMenu').classList.remove('show');document.querySelectorAll('[data-planmode]').forEach(b=>b.onclick=()=>setPlanMode(b.dataset.planmode));$('#planNormalBtn').onclick=()=>setPlanMode('normal');$('#planUndoBtn').onclick=undoPlanChange;
$('#planHistoryBtn').onclick=()=>{showPlanHistory();$('#planMenu').classList.remove('show')};$('#planHistoryClose').onclick=()=>$('#planHistory').classList.remove('show');$('#autoNumberBtn').onclick=()=>{$('#planMenu').classList.remove('show');$('#planAutoNum').classList.add('show');autoNumberPreview()};$('#autoGroup').oninput=autoNumberPreview;$('#autoStart').oninput=autoNumberPreview;$('#autoCancel').onclick=()=>$('#planAutoNum').classList.remove('show');$('#autoApply').onclick=applyAutoNumber;
$('#planAddCancel').onclick=()=>$('#planAdd').classList.remove('show');$('#planAddSave').onclick=saveAddedMelder;$('#planAddNumMode').onchange=()=>{$('#planAddAddr').disabled=$('#planAddNumMode').value==='auto';$('#planAddGroup').disabled=$('#planAddNumMode').value!=='auto'};$('#planAddNumMode').onchange();$('#planManualCancel').onclick=()=>$('#planManualNum').classList.remove('show');$('#planManualSave').onclick=applyManualNumber;
$('#feedbackSuggestionBtn').onclick=()=>{$('#planMenu').classList.remove('show');openFeedback('Vorschlag')};$('#feedbackBugBtn').onclick=()=>{$('#planMenu').classList.remove('show');openFeedback('Funktioniert nicht')};document.querySelectorAll('[data-ft]').forEach(b=>b.onclick=()=>{feedbackType=b.dataset.ft;document.querySelectorAll('[data-ft]').forEach(x=>x.classList.toggle('on',x===b));updateFeedbackDiag()});$('#feedbackSave').onclick=()=>storeFeedback(true);$('#feedbackShare').onclick=shareFeedback;$('#feedbackClose').onclick=()=>$('#feedbackSheet').classList.remove('show');

$('#go').onclick=()=>{cq=sel;$('#qb').textContent=cq;$('#gate').classList.remove('show');persist();if(cq==='Montage')view('p');render()};
persist();
})();
